version: '3.9'


services:
  aiogram:
    build: ./
    container_name: seajoba
    restart: always
    command: ./commands/seajoba.sh
    volumes:
      - ./commands:/commands
      - ./core:/core
      - ./alembic.ini:/alembic.ini
      - ./bot.py:/bot.py
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file:
      - .env

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
